language: node_js
node_js:
  - "4.2.1"
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  - TEST_DIR=.
  - TEST_DIR=viewer
script: cd $TEST_DIR && npm install && npm test
