language: node_js
services:
  - xvfb

node_js:
  - 10

addons:
  chrome: stable

before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sleep 3'
env:
  - TEST_DIR=.
  - TEST_DIR=viewer
script: cd $TEST_DIR && npm install && npm test
